config/routes.rb
Rails.application.routes.draw do
  
  get 'items/create'

  get 'users/update'

  devise_for :users
    resources :users, only: [:update, :show]
      resources :items, only: [:create, :destroy]

  get 'welcome/index'
  get 'welcome/about'
  root to: 'users#show'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  default_scope { order('updated_at ASC') }

  validates :name, presence: true
  
  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items


  def admin?
    role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @user = current_user
    @item = Item.new 
#    authorize @item
  end

  def create
    @user = current_user
    @items = @user.items

    @item = current_user.items.build( items_params )
    @new_item = Item.new
    
#    authorize @item
    if @item.save
      flash[:notice] = "New to-do item created."
    else
      flash[:error] = "There was an error creating your to-do. Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end

  end


  def destroy
    @user = current_user
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "To-do item completed and deleted."
    else
      flash[:error] = "To-do couldn't be deleted. Try again."
    end

    respond_to do |format|
       format.html
       format.js
     end

  end


  private

  def items_params
    params.require(:item).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated."
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information."
      redirect_to edit_user_registration_path
    end
  end

  def show
    @user = current_user
    @items = @user.items
    @item = Item.new
  end


  private

  def user_params
    params.require(:user).permit(:name)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for @user.items.build, remote: true do |f| %>
  
  <div class="form-group">
    <%= f.label :name, "New To-Do Item:" %>
    <%= f.text_area :name, rows: 2, class: 'form-control', placeholder: "Add your to-do here." %>
  </div>

  <div class="form-group">
    <%= f.submit "Create To-Do", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/items/_item.html.erb
<div class="row" id="item-<%= item.id %>">
  <div class="col-md-8">
    <p>
      <%= item.name %>
      <small><i>     You have 
        <%= pluralize(item.days_left, 'day') %>
        left to complete.</i></small>
      <%= link_to "", item, method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
    </p>
  </div>
</div>

app/views/items/create.html.erb
<div class="col-md-8">
  <%= render partial: 'form' %>
</div>

app/views/items/create.js.erb
<% if @item.valid? %>
   $('.js-items').append("<%= escape_javascript(render(@item)) %>");
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { item: @new_item }) %>");
   $('ul.nav').after("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
 <% else %>
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form') %>");
   $('ul.nav').after("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
 <% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
   $('#item-<%= @item.id %>').remove();
   $('ul.nav').after("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
 <% else %>
   $('ul.nav').after("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>


</body>
</html>

app/views/users/show.html.erb
<div class="user-profile">
  <center>
    <h1>My To Do List:</h1>
    <p> ... </p>
  </center>
</div>

<div class="row">
  <div class="col-md-8">
    <div class='js-items'>
      <%= render partial: 'items/item', collection: @items %>
    </div>
    <div class='new-item'>
      <%= render partial: 'items/form' %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Blocitoff</h1>
<p>Blocitoff is a self-destructing to-do list to keep you focused on the things that really matter. Made by Brigid Prinsloo</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccitoff</h1>
  <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Sign up</h2>
    <p>Create your free account to start using Blocitoff immediately.</p>
  </div>
  <div class="col-md-4">
    <h2>Create to-do's</h2>
    <p>Create unlimited to-do items and mark them off as you complete them.</p>
  </div>
  <div class="col-md-4">
    <h2>7 days or bust</h2>
    <p>To-do items will self-destruct after 7 days so you better get started immediately.</p>
  </div>
</div>